server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/estudiantedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 442242

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect